### ISSUE TITLE
SATA identify doesn't work on VirtualBox

### ISSUE THREAD

**Issue by omarrx024** [omarrx024/xos#1]
I am currently aware of this issue. When using SATA on VirtualBox, the identify command always times out, and somehow the task file register reads 0x00, which is not even a normal value to be read, and most likely means the device is not present on that AHCI port, though the signature does indicate it is a SATA device. Will look into this soon. It works in QEMU, though.

**Comment by nkeck720** [comment]
I will test this to see if it happens in Bochs and/or real hardware if I get to it. I saw this project on the FASM forum and thought I might drop by.

**Comment by TheCool1James** [comment]
You might need to add a SATA controller when testing the OS in virtual box
