### ISSUE TITLE
Networking works on more cards than displayed in README

### ISSUE THREAD

**Issue by fido2020** [omarrx024/xos#15]
Hey, i wanted to test your web browser on VirtualBox and I found out that all 3 of the Intel network cards VirtualBox can emulate work with xOS which are Intel PRO/1000 MT Server (82545EM), PRO/1000 T Server (82543GC) and PRO/1000 MT Desktop (82540EM)

**Comment by omarrx024** [comment]
Hi @fido2020 

This is not an issue, it's a feature. I said xOS supports i8254x (aka E1000) network cards, and all the Intel PRO/1000 cards belong to the i8254x family, and thus all of them can be controlled by one compatible driver. I know that all Intel PRO/1000 cards work.
