### ISSUE TITLE
xOS floppy image - is it possible?

### ISSUE THREAD

**Issue by informer2016** [omarrx024/xos#21]
No I am not going to use any real physical floppies, although maybe someone would ;) There is open source coreboot+SeaBIOS replacement of the "official BIOS" which supports these motherboards: https://www.coreboot.org/Supported_Motherboards _(maybe you have something from this list?!)_

This coreboot+SeaBIOS combination occupies just a small fraction of the BIOS chip volume - and could boot any virtual floppy image if you put it to a BIOS chip as well. So: if your laptop/motherboard is supported by coreboot project, you could boot xOS floppy right from a BIOS chip - which is super cool!

I see that xOS disk.hdd is 32 MB - way too large... but your zip archive with that disk image - weights just 500 KB ! If xOS could be compressed that easily, it should be possible to somehow compress the majority of xOS except the booting part and unarchiver, then while booting it decompresses that "main part" and loads it to RAM... If that really has to be done **_(I don't know, maybe xOS occupies just a tiny fraction of that 32 MB image and no compression is necessary to fit it to 1.44MB ?)_**

There is another modern OS written in assembly - KolibriOS - which is distributed as a floppy image. It would be great if xOS would also have a floppy image, making it possible to boot from a BIOS chip and probably some other purposes... What do you think about this idea?

**Comment by omarrx024** [comment]
Possible, yes -- practical, no.

Booting from floppy is possible if I implement a floppy driver, but that's mostly a waste of time considering nobody uses floppies anymore. The xOS binaries without the data is less than half a megabyte, as you may have noticed. The hard disk image is mostly empty space.
