### ISSUE TITLE
Dead project?

### ISSUE THREAD

**Issue by BrownieOS** [omarrx024/xos#22]
I just came here, and saw that xOS is dead! Is lux replacing xOS? And, could I fork xOS, and continue the project?

**Comment by omarrx024** [comment]
Yes, xOS is dead and I don't do any more work on it. lux is my active OS project with much bigger goals. And yes, xOS is MIT-licensed, so yes, you (and everybody else) are allowed to fork it and continue it as long as I receive original credit.
