### ISSUE TITLE
UI Improvements and Terminal/Shell

### ISSUE THREAD

**Issue by fido2020** [omarrx024/xos#3]
Sorry if this is not the best place to put this but i dont know where else too. Anyway, i think the UI needs quite a lot of improving in xOS and i think the next things you should work on are - Window Closing ( turn those red squares on the windows into close buttons), Menu (Add a menu button that comes up with a list of programs) also - Terminal/Shell (To provide another way to interface with the OS, basic commands like viewing and creating directories and files and also adding basic scripting) I am not expecting these things to be added any time soon but i think these are things that should be implemented when you have the time

**Comment by omarrx024** [comment]
Thanks for your feedback. Window closing and task termination are the high things in my priority list for now. I don't have plans for a command-line shell, but I have a graphical shell planned. These things can be expected to be seen in the coming month. Recently, though, I fixed (rewrote, really) my AHCI driver and wrote the skeleton for USB support.
